Support ABI Data passing in near calls
* Add nearcall intrinsic to call a function with ABI data.
* Reserve `R15` in calling convention for ABI data passing

Co-author: Alan Li

diff --git a/.github/workflows/llvm-back-end.yml b/.github/workflows/llvm-back-end.yml
--- a/.github/workflows/llvm-back-end.yml
+++ b/.github/workflows/llvm-back-end.yml
@@ -49,6 +49,28 @@ jobs:
           exit 1
         fi
 
+    - name: Get branch name (merge)
+      if: github.event_name != 'pull_request'
+      shell: bash
+      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
+
+    - name: Get branch name (pull request)
+      if: github.event_name == 'pull_request'
+      shell: bash
+      run: echo "BRANCH_NAME=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
+
+    - name: Set compiler-tester branch depending on current branch
+      shell: bash
+      run: |
+        if [[ "${BRANCH_NAME}" == "main" ]]; then
+          echo "COMPILER_BRANCH_NAME=main" >> $GITHUB_ENV
+        elif [[ "${BRANCH_NAME}" == "dev-1.1" ]]; then
+          echo "COMPILER_BRANCH_NAME=vm1.1" >> $GITHUB_ENV
+        else
+          echo "Cannot map current branch to compiler-tester branch"
+          exit 1
+        fi
+
     - name: Preparing workspace. Checkout compiler-tester repository.
       uses: actions/checkout@v2
       with:
