Testing benchmarking results as artifacts

diff --git a/.github/workflows/llvm-benchmarks.yml b/.github/workflows/llvm-benchmarks.yml
--- a/.github/workflows/llvm-benchmarks.yml
+++ b/.github/workflows/llvm-benchmarks.yml
@@ -17,7 +17,7 @@ on:
         default: "main"
 
 jobs:
-  llvm_benchmarks:
+  llvm_benchmarks_candidate:
     runs-on: [self-hosted, compiler]
     steps:
       - uses: AutoModality/action-clean@v1
@@ -27,8 +27,8 @@ jobs:
       - name: Preparing workspace. Setting environment.
         run: |
           echo "COMPOSE_FILE=${{github.workspace}}/compiler-llvm/infra/docker-compose.yml" >> $GITHUB_ENV
-          echo "COMPOSE_PROJECT_NAME=llvm_benchmarks" >> $GITHUB_ENV
-          echo "DOCKER_CMD=docker compose exec -T zk" >> $GITHUB_ENV
+          echo "COMPOSE_PROJECT_NAME=llvm_benchmarks_candidate" >> $GITHUB_ENV
+          echo "DOCKER_CMD=docker compose exec -T zk_candidate" >> $GITHUB_ENV
           echo "LLVM_BUILD_TYPE=${{ github.event.inputs.llvm_build_type || 'release'}}" >> $GITHUB_ENV
 
       - name: Get branch name (pull request)
@@ -69,16 +69,10 @@ jobs:
         with:
           path: compiler-llvm
 
-      # - name: Preparing workspace. Checkout compiler-llvm reference.
-      #   uses: actions/checkout@v2
-      #   with:
-      #     path: compiler-llvm-reference
-      #     ref: ${{ env.BRANCH_NAME }}
-
       - name: Preparing workspace. Start Docker container for candidate.
         run: |
           docker compose pull
-          docker compose up -d zk
+          docker compose up -d zk_candidate
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PK_BOT }}
 
@@ -105,49 +99,193 @@ jobs:
           git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://github.com/ && \
           export LLVM_SYS_130_PREFIX=${HOME}/opt/llvm-${{ env.LLVM_BUILD_TYPE }}/ && \
           cargo run --release --bin compiler-tester -- -v --filter=${FILTER} --domain=${DOMAIN} --benchmark=candidate.json'
-          # compiler_exit_code=$?
-          # if [ "${compiler_exit_code}" -gt "1" ]; then
-          #   echo "RUN_SEGFAULT_STEP=true" >> $GITHUB_ENV
-          # fi
 
       - uses: actions/upload-artifact@v3
         with:
           name: compiler-llvm-candidate-benchmark
           path: compiler-tester/candidate.json
 
-      # - name: Testing. Running regression LLVM tests.
-      #   run: |
-      #     ${DOCKER_CMD} sh -c '
-      #     cd compiler-llvm/build-${{ env.LLVM_BUILD_TYPE }} && \
-      #     make -j24 check-llvm-codegen-syncvm'
+      - name: Clearing workspace. Removing used and trash docker images.
+        if: always()
+        run: |
+          docker image prune -f --all
+          docker compose down --rmi local -v
 
-      # - name: Testing. Benchmarking and comparing compiler-llvm.
-      #   id: compiler_tester_run
-      #   run: |
-      #     ${DOCKER_CMD} sh -c '
-      #     cd compiler-tester && \
-      #     git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/ && \
-      #     git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://github.com/ && \
-      #     export LLVM_SYS_130_PREFIX=${HOME}/opt/llvm-${{ env.LLVM_BUILD_TYPE }}/ && \
-      #     cargo run --verbose --release --bin compiler-tester'
-      #     compiler_exit_code=$?
-      #     if [ "${compiler_exit_code}" -gt "1" ]; then
-      #       echo "RUN_SEGFAULT_STEP=true" >> $GITHUB_ENV
-      #     fi
+  llvm_benchmarks_reference:
+    runs-on: [self-hosted, compiler]
+    steps:
+      - uses: AutoModality/action-clean@v1
+      - uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PK_BOT }}
+      - name: Preparing workspace. Setting environment.
+        run: |
+          echo "COMPOSE_FILE=${{github.workspace}}/compiler-llvm/infra/docker-compose.yml" >> $GITHUB_ENV
+          echo "COMPOSE_PROJECT_NAME=llvm_benchmarks_reference" >> $GITHUB_ENV
+          echo "DOCKER_CMD=docker compose exec -T zk_reference" >> $GITHUB_ENV
+          echo "LLVM_BUILD_TYPE=${{ github.event.inputs.llvm_build_type || 'release'}}" >> $GITHUB_ENV
 
-      # - name: Testing. Running segfault.sh.
-      #   if: always() && steps.compiler_tester_run.outcome == 'failure' && env.RUN_SEGFAULT_STEP == 'true'
-      #   run: ${DOCKER_CMD} sh -c 'cd compiler-tester && ./segfault.sh'
+      - name: Get branch name (pull request)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: echo "BRANCH_NAME=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
 
-      # - name: Notify to Mattermost (on unsuccessful deploys)
-      #   if: failure() || cancelled()
-      #   uses: tferreira/matterfy@releases/v1
-      #   with:
-      #     type: ${{ job.status }}
-      #     job_name: "*LLVM testing is failed*"
-      #     icon_emoji: octocat
-      #     channel: "compiler-llvm-ci"
-      #     url: ${{ secrets.MATTERMOST_WEBHOOK }}
+      - name: Set compiler-tester branch depending on current branch (pull request)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: |
+          if [[ "${BRANCH_NAME}" == "main" ]]; then
+            echo "COMPILER_TESTER_BRANCH_NAME=main" >> $GITHUB_ENV
+          elif [[ "${BRANCH_NAME}" == "dev-1.1" ]]; then
+            echo "COMPILER_TESTER_BRANCH_NAME=vm1.1" >> $GITHUB_ENV
+          else
+            echo "Cannot map current branch to compiler-tester branch"
+            exit 1
+          fi
+
+      - name: Set compiler-tester branch from manual input (workflow dispatch)
+        if: github.event_name == 'workflow_dispatch'
+        shell: bash
+        run: |
+          echo "COMPILER_TESTER_BRANCH_NAME=${{ github.event.inputs.compiler_tester_branch }}" >> $GITHUB_ENV
+
+      - name: Preparing workspace. Checkout compiler-tester repository.
+        uses: actions/checkout@v2
+        with:
+          repository: matter-labs/compiler-tester
+          ref: ${{ env.COMPILER_TESTER_BRANCH_NAME }}
+          submodules: recursive
+          token: ${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}
+          path: "compiler-tester"
+
+      - name: Preparing workspace. Checkout compiler-llvm reference.
+        uses: actions/checkout@v2
+        with:
+          path: compiler-llvm
+          ref: ${{ env.BRANCH_NAME }}
+
+      - name: Preparing workspace. Start Docker container for reference.
+        run: |
+          docker compose pull
+          docker compose up -d zk_reference
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PK_BOT }}
+
+      - name: Preparing workspace. Setting docker ssh key.
+        run: |
+          ${DOCKER_CMD} sh -c 'mkdir -pv /root/.ssh'
+          ${DOCKER_CMD} sh -c 'echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa'
+          ${DOCKER_CMD} sh -c 'chmod 400 /root/.ssh/id_rsa'
+          ${DOCKER_CMD} sh -c 'touch /root/.ssh/known_hosts'
+          ${DOCKER_CMD} sh -c 'ssh-keyscan github.com >> /root/.ssh/known_hosts'
+
+      - name: Testing. Building LLVM framework reference.
+        run: |
+          chmod +x compiler-llvm/build.sh
+          ${DOCKER_CMD} sh -c 'cd compiler-llvm && \
+          ./build.sh ${{ env.LLVM_BUILD_TYPE }}'
+
+      - name: Testing. Benchmarking  LLVM framework reference.
+        id: compiler_tester_run
+        run: |
+          ${DOCKER_CMD} sh -c '
+          cd compiler-tester && \
+          git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/ && \
+          git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://github.com/ && \
+          export LLVM_SYS_130_PREFIX=${HOME}/opt/llvm-${{ env.LLVM_BUILD_TYPE }}/ && \
+          cargo run --release --bin compiler-tester -- -v --filter=${FILTER} --domain=${DOMAIN} --benchmark=reference.json'
+
+      - uses: actions/upload-artifact@v3
+        with:
+          name: compiler-llvm-reference-benchmark
+          path: compiler-tester/reference.json
+
+      - name: Clearing workspace. Removing used and trash docker images.
+        if: always()
+        run: |
+          docker image prune -f --all
+          docker compose down --rmi local -v
+
+  llvm_benchmarks_analysis:
+    runs-on: [self-hosted, compiler]
+    steps:
+      - uses: AutoModality/action-clean@v1
+      - uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PK_BOT }}
+      - name: Preparing workspace. Setting environment.
+        run: |
+          echo "COMPOSE_FILE=${{github.workspace}}/compiler-llvm/infra/docker-compose.yml" >> $GITHUB_ENV
+          echo "COMPOSE_PROJECT_NAME=llvm_benchmarks_analysis" >> $GITHUB_ENV
+          echo "DOCKER_CMD=docker compose exec -T zk_analysis" >> $GITHUB_ENV
+
+      - name: Get branch name (pull request)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: echo "BRANCH_NAME=$(echo ${GITHUB_BASE_REF} | tr / -)" >> $GITHUB_ENV
+
+      - name: Set compiler-tester branch depending on current branch (pull request)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: |
+          if [[ "${BRANCH_NAME}" == "main" ]]; then
+            echo "COMPILER_TESTER_BRANCH_NAME=main" >> $GITHUB_ENV
+          elif [[ "${BRANCH_NAME}" == "dev-1.1" ]]; then
+            echo "COMPILER_TESTER_BRANCH_NAME=vm1.1" >> $GITHUB_ENV
+          else
+            echo "Cannot map current branch to compiler-tester branch"
+            exit 1
+          fi
+
+      - name: Set compiler-tester branch from manual input (workflow dispatch)
+        if: github.event_name == 'workflow_dispatch'
+        shell: bash
+        run: |
+          echo "COMPILER_TESTER_BRANCH_NAME=${{ github.event.inputs.compiler_tester_branch }}" >> $GITHUB_ENV
+
+      - name: Preparing workspace. Checkout compiler-tester repository.
+        uses: actions/checkout@v2
+        with:
+          repository: matter-labs/compiler-tester
+          ref: ${{ env.COMPILER_TESTER_BRANCH_NAME }}
+          submodules: recursive
+          token: ${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}
+          path: "compiler-tester"
+
+      - name: Preparing workspace. Start Docker container for reference.
+        run: |
+          docker compose pull
+          docker compose up -d zk_analysis
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PK_BOT }}
+
+      - name: Preparing workspace. Setting docker ssh key.
+        run: |
+          ${DOCKER_CMD} sh -c 'mkdir -pv /root/.ssh'
+          ${DOCKER_CMD} sh -c 'echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa'
+          ${DOCKER_CMD} sh -c 'chmod 400 /root/.ssh/id_rsa'
+          ${DOCKER_CMD} sh -c 'touch /root/.ssh/known_hosts'
+          ${DOCKER_CMD} sh -c 'ssh-keyscan github.com >> /root/.ssh/known_hosts'
+
+      - uses: actions/download-artifact@master
+        with:
+          name: compiler-llvm-candidate-benchmark
+          path: compiler-tester
+
+      - uses: actions/download-artifact@master
+        with:
+          name: compiler-llvm-candidate-reference
+          path: compiler-tester
+
+      - name: Testing. Comparing LLVM framework results.
+        id: compiler_tester_run
+        run: |
+          ${DOCKER_CMD} sh -c '
+          cd compiler-tester && \
+          git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com/ && \
+          git config --global url."https://${{ secrets.COMPILER_TESTER_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://github.com/ && \
+          export LLVM_SYS_130_PREFIX=${HOME}/opt/llvm-${{ env.LLVM_BUILD_TYPE }}/ && \
+          cargo run --release --bin benchmark-analyzer -- --reference reference.json --candidate candidate.json
 
       - name: Clearing workspace. Removing used and trash docker images.
         if: always()
